version: '3.6'
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  balancer:
    build: ./nginx
    networks:
      backend:
        ipv4_address: 10.5.0.2
    privileged: true
    environment:
      NGINX_HOST: "localhost"
      NGINX_SSL: "OFF"
      NGINX_PROD: "OFF"
    volumes:
      - "./nginx/nginx2.conf:/etc/nginx/nginx.conf"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.j2"
      - "./data/storage/public:/uploads-public"
      - "./nginx/pass/explorer.txt:/etc/nginx/passwords/explorer.txt"
      -  ./typo3:/typo3
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "j2 /etc/nginx/conf.d/default.j2 > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
       - php
    logging:
      options:
        max-size: 1000m
    restart: 'no'

  php:
    image: php:7-fpm
    networks:
      backend:
        ipv4_address: 10.5.0.3
    volumes:
      - ./typo3:/typo3

#
#  mysql:
#    image: mariadb
#    networks:
#      backend:
#          ipv4_address: 10.5.0.11
#    ports:
#      - "3306:3306"
#    volumes:
#      - "./data/mysql/etc:/etc/mysql"
#      - "./data/mysql/log:/var/log/mysql"
#      - "./data/mysql/mysqldb:/var/lib/mysql/data"
#      - "/private/var/run/mysql:/var/run/mysql"
#      - "./data/backup:/usr/src/backup"
#    environment:
#      MYSQL_ROOT_PASSWORD: train999
#      MYSQL_MULTIPLE_DATABASES: mrsbase
#      MYSQL_PASSWORD: UU6iyHsoTxAUznVgJDjewr8S
#      MYSQL_USER: mrs
#      MYSQL_HOST: mysql
#      DEBUG: "true"
#    logging:
#      options:
#        max-size: 1000m
#    restart: 'no'
#
#  phpmyadmin:
#    image: corbinu/docker-phpmyadmin
#    networks:
#      backend:
#        ipv4_address: 10.5.0.12
#    depends_on:
#      - mysql
#    ports:
#      - 8181:80
#    environment:
#      MYSQL_USERNAME: root
#      MYSQL_ROOT_PASSWORD: train999
#

